[package]
name = "entity-twin-runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde.workspace = true
# Add other dependencies specific to this crate
